GeckoTH/arkham-horror

o8g/definition.xml

The [player summary must be defined](https://github.com/octgn/OCTGN/wiki/definition.xml#player). We'll set this to something better, but just showing the hand size for now.

Fixes lobby dialogue not popping up

---

o8g/Scripts/actions.py
o8g/definition.xml

Convert tabs to spaces since that's what in the [Python Style Guide, PEP-8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces).

Tabs to Spaces

---

o8g/Scripts/actions.py
o8g/definition.xml

Upon loading a player deck, it should also place the Investigator and mini card out on the table, and draw your starting hand

Get Player Setup working.

---

o8g/Scripts/actions.py
o8g/definition.xml

Add the shortcuts and mneu options of the doom token

Doom Tokens

---

o8g/Scripts/actions.py
o8g/Sets/Markers and Tokens/set.xml

This also prevents the discard function from blowing up

get chaos tokens discarding back into the chaos bag

---

o8g/Scripts/actions.py

This implements double clicking the encounter deck (or Ctrl+E). It places them in the "staging" area. It still leaves room for the Chaos Token to be drawn.

Encounter Draw

---

o8g/Scripts/actions.py

This correctly draws the opening hand by replacing weakness cards with non weakness cards.

replace weakness cards in opening hand

---

o8g/Decks/01 - Core/3 - The Devourer Below.o8d

This adds the cultists you might need.

Add cultists for those who got away

---

.gitignore
o8g/Scripts/actions.py
o8g/definition.xml

Minor fixes

---

o8g/Scripts/actions.py
o8g/definition.xml

This removes the lotr phase management code, cleans up turn management menu to reflect that, and fixes Upkeep/End of Round management.

Automate End of Round Management

---

o8g/definition.xml

Set Rotate shortcut keys to F8/F9 as discussed.

Set Rotate shortcut keys to F8/F9

---

o8g/definition.xml

The old comments were blocking the new round functions.

Remove old comments, consolidate Automation menus

---

o8g/Scripts/actions.py

This fixes a few issues around isSpecialCard and setController.  Resolves Issue #52.

Fixes isSpecialCard and setController issues.

---

o8g/Scripts/actions.py

This fixes the "Inconsistent State" warning when advancing the phase.

Inconsistent State marker fix

---

o8g/Scripts/actions.py
o8g/definition.xml

Updated draw X chaos tokens function to account for new draw methods. This PR now allows any player to draw X chaos tokens!

Allow any player to draw X chaos tokens

---

o8g/Scripts/actions.py

Cards will now fan out when loading a scenario!

Fix the process to fan cards when loading a scenario.

---

o8g/Scripts/actions.py

Check for hand size during upkeep (or ctrl-n) and show dialog for player to select cards to discard.

Check for hand size during upkeep (or ctrl-n)

---

o8g/Decks/02 - Dunwich Legacy/1a - Extracurricular Activity.o8d

Added The Experiment to Extracurricular Activity global setup

Added The Experiment to Extracurricular Activity

---

o8g/Scripts/plugin.py
o8g/Scripts/util.py
o8g/definition.xml

New features introduced including:
- Ctrl+Shift+X to move card to a shared Trash Pile
- Saving the local player's deck (investigator+deck) to o8d format
- Save/Load the game state, including cards on tables/shared pile/player hand and piles/counters. 
Please note the script version and game version are not updated in the definition.xml

Introduce new script features

---

o8g/Sets/The Circle Undone/set.xml

Witches' Circle is the back of Act 3a Paths into Twilight.
Josef's Plan is the back of Josef Meiger enemy.

Merge card front & back

---

o8g/Sets/Shattered Aeons/set.xml

10 locations in this set is fixed to be single-sided, from being double-sided.

Fixed single-sided locations

---

o8g/Scripts/actions.py
o8g/Scripts/plugin.py
o8g/Sets/The Dream-Eaters/set.xml
o8g/definition.xml

This PR has adjustments to #149 and #150, and should be merged at the end.

Octgn update

---

o8g/Scripts/actions.py
o8g/definition.xml

OnScriptedCardsMoved (like doubleClick)

fix autoCharges and autoClues

---

o8g/Decks/102 - Carnevale of Horrors/Carnevale of Horrors - Campaign Version.o8d
o8g/Decks/102 - Carnevale of Horrors/Carnevale of Horrors - Standalone Hard Difficulty.o8d
o8g/Decks/102 - Carnevale of Horrors/Carnevale of Horrors - Standalone Standard Difficulty.o8d
o8g/Sets/Carnevale of Horrors/set.xml

Issues #197 and #198 have been fixed

Fixes on carnavale

---

o8g/Decks/01 - Night of the Zealot/3 - The Devourer Below.o8d
o8g/Decks/01R - Return to the Night of the Zealot/3 - Return to The Devourer Below.o8d

Set quantity for Umôrdhoth's Wrath in Devourer Below and Return to Devourer Below to 2.

Fix Umôrdhoth's Wrath qty in Devourer Below

---

o8g/Scripts/actions.py
o8g/Sets/Return to the Circle Undone/set.xml
o8g/definition.xml

Adding the Ability to draw a single Card in upright direction, or do a 1-, 2-, or 3-Card Reading.

Adding script to draw Tarot Cards

---

o8g/Scripts/actions.py
o8g/Scripts/card_automation.py
o8g/definition.xml

Moved Default Action to card_automation.py and created a search function that checks if Mandy is on the table, cancels if Shocking Discovery is found and looks for specified traits if specified.

Implementing Automated Card Search

---

o8g/Sets/Edge of the Earth Campaign Expansion/set.xml

- Fixed Tekeli-li player back cards
- Fixed "Lost in the night scenario" encounter back to Story cards
- Fixed small typo on Polar Vortex

EotE Fixes

---

o8g/Sets/Edge of the Earth Campaign Expansion/set.xml

Possessed and Frostbitten need a player card back

EotE Campaign Weakness fixes

---

o8g/Scripts/actions.py
o8g/Scripts/blurse.py
o8g/Scripts/card_automation.py
o8g/Scripts/phase_change_automation.py

- Changed most of the owner checks of cards back to controller
- Fixed some bugs (Norman deck flipping twice, Forced Learning not working and many cards that seal tokens)

Control fix

---

o8g/Decks/02R - Return to the Dunwich Legacy/7 - Return to Lost in Time and Space.o8d

Encounter is missing the 3 added locations from Return to

Update 7 - Return to Lost in Time and Space.o8d

---

o8g/Decks/09 - The Scarlet Keys/File #28-I - Dancing Mad (v. I).o8d
o8g/Scripts/actions.py
o8g/Scripts/bonded.py
o8g/Scripts/card_automation.py
o8g/Scripts/phase_change_automation.py
o8g/Sets/Return to the Path to Carcosa/set.xml
o8g/Sets/The Scarlet Keys Campaign Expansion/set.xml
o8g/Sets/The Scarlet Keys Investigator Expansion/set.xml

added resources for makeshift trap, jury-rig, and shrine of the moirai. this works for all events that have Uses(x charges). fix for runic axe
fix for vincent's on the mend
fix for darrell's kodak

Minor changes

---

o8g/Scripts/actions.py
o8g/Scripts/blurse.py
o8g/Scripts/card_automation.py
o8g/definition.xml

The initial changes are:
Remove bless / curse menu items.  Automation for 5U-21.  Automation for Darrell's Kodak.  Automation for William Yorick.

Minor changes requested by Ken

---

o8g/Scripts/actions.py
o8g/Scripts/card_automation.py

Added Kohaku automation + Book of Living Myths automation
Fixed Shards of the Void

Kohaku Narukami automation
