- o8g/Scripts/actions.py
- o8g/definition.xml
This adds the ability to draw a Chaos Token from the Chaos "Bag". If you double click on the global "Chaos Bag" pile, it will shuffle the pile before drawing a new one. In addition, "Ctrl+S" draws a new Chaos Token. I was just trying to pick a shortcut that wasn't used but open to suggestions. There's an option listed under the Table menu. Finally, if an existing token on the board already exists, it will automatically shuffle that one back in before drawing a new one, so there's no need to manually discard when doing multiple tests.
> draw chaos token

- o8g/Scripts/actions.py
I mucked around with positioning. `cardHere` is kind of wonky. Here's what it looks like in this PR.
> correctly position encounter deck: act, agenda, and scenario cards

- o8g/Scripts/actions.py
This auto shuffles the encounter discard into the encounter pile on deck load setup.
> on deck load, shuffle encounter discard into encounter deck

- o8g/Scripts/actions.py
Currently, when drawing a chaos token blows up if the chaos bag is empty. This guards that.
> draw token should not blow up when the bag is empty

- o8g/Scripts/actions.py
This simply calls the `nextActStage` and `nextAgendaStage` functions when double clicked on. I'm not sure if you wanted it to put the card on top of the existing Act/Agenda. I assumed so, since there's a nice spot for it in the "book". Secondly, it first flips to Side B if Side A is showing. This means you'll need to double click twice to get an Agenda or Act replaced.
> Draw act/agenda

- o8g/Decks/01 - Core/Basic Weaknesses.o8d
- o8g/Scripts/actions.py
- o8g/Scripts/basic_weakness.py
- o8g/definition.xml
This is a spike on how I think the Random Basic Weakness drawing could be done. It sets up a separate Basic Weakness deck for the Core Set with a separate shared pile. There's a menu when right clicking to draw one into your deck.
There is one caveat, since we're autodrawing people's hands this step should happen first. People can just use the mulligan function from #16. We could also autodraw people's hands when they take a Mulligan with a confirm dialogue?
@GeckoTH you should probably double check I did this right and it has the right cards.
> Basic Weakness

- o8g/Scripts/actions.py
- o8g/definition.xml
This adds locations into the "staging" area, where the encounter cards go. Both double clicking the location deck or right click "reveal next location" do the same thing.
> revealing the next location puts it into the staging area

- o8g/Scripts/actions.py
double clicking on the library doesn't crash and places card on the table. the `eliminated` method is not really implemented yet though.
> fix playCard

- o8g/Scripts/actions.py
- o8g/Scripts/basic_weakness.py
- o8g/definition.xml
This reworks how basic weaknesses are handled based on the discord discussion yesterday:
* Created a player pile for holding the basic weaknesses that is collapsed by default.
* Draw Basic Weakness option from the player library will now first populate the new pile and draw from the top of it after shuffling
* There is a context menu for basic weakness for loading the deck
* Whenever the basic weakness deck is loaded, it'll scan the table (player owned), hand, deck, discard for the subtype "Basic Weakness" and remove those before creating the deck. This should prevent any dupes from entering play.
With these changes when needed a player can examine the Basic Weakness deck and pull the top card for a random draw or look through if a specific one one is needed.
> Rework Basic Weaknesses

- o8g/definition.xml
This is for holding cards which don't count against the card limit, to simplify counting cards for the deck limit. Specifically to help when building decks with services like arkhamdb.com, where they keep cards that don't count against the player limit in separate sections.
> Add section for holding special cards in deck.

- o8g/Scripts/actions.py
- o8g/definition.xml
This leverages the Basic Weakness deck when drawing a Basic Weakness. It should limit the available weaknesses to those out of play.
> Add ability to draw a Basic Weakness into your hand.

- o8g/Scripts/actions.py
- o8g/definition.xml
This highlights the agenda card when the doom level is greater or equal to the card's doom level. If the doom counter goes below, the highlight is removed. I'm using the color red for the highlight.
> highlight agenda card when hit doom level

- o8g/Scripts/actions.py
These are used in POD expansions, and in the Strange Eons custom scenarios. This PR places campaign cards to the right of the agenda/act/scenario block when campaign cards are included in a scenario deck.
> Added placement for Campaign cards.

- o8g/definition.xml
OCTGN insists on irrelevant properties for build. I've added in defaults.
> Fix path definitions. OCTGN insists on irrelevant properties for build.

- o8g/Scripts/actions.py
Paths were flipping during Upkeep. They are "anchored" not "locked" (since locked comes with a graphic). Now the upkeep checks for both.
> Locked and Anchored are not the same. Paths now check for both.

- o8g/Scripts/actions.py
- o8g/Scripts/basic_weakness.py
This PR fixes and refactors some bugs with basic weakness loading. In addition, it also adds the dunwich legacy basic weaknesses so they can be easily used. Lastly, since there are multiple sets now in play, a dialogue asks what ones should be used.
> add dunwich legacy basic weaknesses to basic weakness functions

- o8g/Scripts/actions.py
When a player deck is loaded, the deck will be searched for cards with the "Permanent" keyword. Any card found will be sent directly to the table.
> Move Permanents directly to the table.

- o8g/Scripts/actions.py
- o8g/definition.xml
This is very useful for scenarios like Blood on the Altar which require face-down encounter card draws,
> Add ability to draw encounter cards unrevealed

- o8g/Scripts/actions.py
- o8g/definition.xml
The mulligan feature allows you to select the cards you want to replace, and the system will handle the discarding and redrawing, along with annotating the action in the log.
> Added ability to mulligan by right-clicking on hand cards.

- o8g/Decks/02 - Dunwich Legacy/2 - The Miskatonic Museum.o8d
Addresses #114 
There was two copies of Exhibit Hall (Restricted Hall) - one in the Location deck, the other in the Setup deck. In addition there was no copy of Exhibit Hall (Athabaskan Exhibit). I replaced the Restricted Hall in the Location deck with the Athabaskan Exhibit.
> Extra copy of Restricted Hall in MM

- o8g/Decks/05 - The Circle Undone/3 - The Secret Name.o8d
- o8g/Decks/05 - The Circle Undone/4 - The Wages of Sin.o8d
- o8g/Decks/05 - The Circle Undone/5 - For the Greater Good.o8d
- o8g/Decks/05 - The Circle Undone/6 - Union and Disillusion.o8d
- o8g/Decks/05 - The Circle Undone/7 - In the Clutches of Chaos.o8d
- o8g/Decks/05 - The Circle Undone/8 - Before the Black Throne.o8d
- o8g/Decks/05 - The Circle Undone/Prologue - Gavriella Mizrah.o8d
- o8g/Decks/05 - The Circle Undone/Prologue - Penny White.o8d
- o8g/Decks/05 - The Circle Undone/Prologue - Valentino Rivas.o8d
- o8g/Decks/104 - Guardians of the Abyss/1 - The Eternal Slumber.o8d
- o8g/Decks/104 - Guardians of the Abyss/2 - The Night’s Usurper.o8d
- o8g/Sets/Before the Black Throne/set.xml
- o8g/Sets/For the Greater Good/set.xml
- o8g/Sets/Guardians of the Abyss/set.xml
- o8g/Sets/In the Clutches of Chaos/set.xml
- o8g/Sets/The Secret Name/set.xml
- o8g/Sets/The Wages of Sin/set.xml
- o8g/Sets/Union and Disillusion/set.xml
1. Add set and deck files for Guardians of the Abyss and the rest of TCU.
2. Update TCU prologue investigator decks to have all cards in main deck. Before this, some cards were in 2nd deck, which is not obvious to everyone.
3. Multiclass cards from The Secret Name are put as Neutral at the moment.
Great thanks to Ben#9270 for providing set & deck files. I only make some (minor) adjustments and create this pull request. Also thanks to rushl#0214 for teaching me how to do this properly!!
> Add sets & decks

- .gitignore
- README.md
- o8g/Sets/Before the Black Throne/set.xml
- o8g/Sets/For the Greater Good/set.xml
- o8g/Sets/Guardians of the Abyss/set.xml
- o8g/Sets/In the Clutches of Chaos/set.xml
- o8g/Sets/Return to the Path to Carcosa/set.xml
- o8g/Sets/The Dream-Eaters/set.xml
- o8g/Sets/The Secret Name/set.xml
- o8g/Sets/The Wages of Sin/set.xml
- o8g/Sets/Union and Disillusion/set.xml
I removed the standalone-attributes in the new set.xml files, which caused problems with the build tool. Furthermore I also fixed the classes of the multiclass cards introduced in "The Secret Name". E.g. I changed the class of the .45 Thompson from "neutral" to "Guardian/Rogue". This way it's also comes up if you search for "Guardian"-Cards in the Deck-Editor
Lastly I compiled everything into a .nupkg file and provided some Info in the readme to make it easier for new people to install the most recent version of the game.
I tested all changes in OCTGN and couldn't find any immediate problems. Everything seems to work fine as far as I can tell. I am also open for suggestions.
> Make the Repository buildable by the o8build-tool and provide an easier way for people to update their game

- o8g/Scripts/actions.py
- o8g/definition.xml
I added the ability to draw additional tokens, without putting the old ones back into the Bag.
Furthermore I implemented the Seal Mechanic. For this I am utilizing the Subtype property of the Chaos Tokens, since I doubt this will ever be used otherwise. Chaos Tokens with the Subtype "Sealed" will not be automatically removed from the Table. If the Token is discarded, the property is automatically removed again.
Sealed Tokens are currently displayed with a slight grey-filter, since I didn't think of any other way to easily mark them as sealed.
While I did test it with two clients to make sure it also works in Multiplayer, I would like someone else to take a look at it, just in case I missed something. Also I am open for suggestions.
> Chaos Token shenanigans

- o8g/Scripts/actions.py
- o8g/definition.xml
- Fix for the Token keeping the Sealed-Attribute after being moved to the Chaosbag instead of being discarded
- added the possibility to seal a drawn Token by right-clicking it
- bumped the Buildnumber in case the fixes will be deployed before the next pack releases.
(Thanks to Ken for the recommendations)
> Card-Context menu entry to seal Chaostoken directly and Bugfixes

- o8g/Scripts/actions.py
Adresses #205 
The Encounter Deck now only shuffles when it is empty and a card is drawn. When Phase automation is used, the Player Deck now also automatically shuffles when the deck is empty and a card would be drawn. Additionally one Horror is placed on the Investigator.
> Fix Encounter Deck shuffling and automate Player Deck shuffling

- o8g/Scripts/plugin.py
Stop loadTable from trying to open file when user closed or canceled dialog box.
> Fix laodTable trying to open file on cancelation

- o8g/Scripts/actions.py
FIX: Face-down double-sided cards could not be turned face up
FIX: Drawing an unrevealed card displayed the card name in the chat log
FIX: Selecting the "Mulligan" option displayed the cards in the reverse order from the Hand pane
> Minor bug fixes to actions.py

- o8g/Decks/110 - Fortune and Folly/1 - Fortune and Folly, Part I.o8d
The scenario reference card is missing in FnF Part 1.  This adds it.  Without the scenario reference card, when it's loaded in octgn, it'll cause an exception.
> Update to Fortune & Folly part 1
